using System;
using System.Data;
using CalculateFunding.Common.Extensions;
using CalculateFunding.Models.Publishing;
using CalculateFunding.Services.SqlExport;

namespace CalculateFunding.Services.Publishing.SqlExport
{
    public class ProviderDataTableBuilder : DataTableBuilder<PublishedProviderVersion>
    {
        protected override DataColumn[] GetDataColumns(PublishedProviderVersion dto) =>
            new[]
            {
                NewDataColumn<string>("PublishedProviderId", 128),
                NewDataColumn<string>("ProviderId", 32),
                NewDataColumn<string>("ProviderName", 256),
                NewDataColumn<string>("UKPRN", 32),
                NewDataColumn<string>("URN", 32, allowNull: true),
                NewDataColumn<string>("Authority", 256, allowNull: true),
                NewDataColumn<string>("ProviderType", 128),
                NewDataColumn<string>("ProviderSubType", 128),
                NewDataColumn<DateTime>("DateOpened", allowNull: true),
                NewDataColumn<DateTime>("DateClosed", allowNull: true),
                NewDataColumn<string>("LaCode", 32, allowNull: true),
                NewDataColumn<string>("Status", 64, true),
                NewDataColumn<string>("Successor", 128, true),
                NewDataColumn<string>("TrustCode", 32, allowNull: true),
                NewDataColumn<string>("TrustName", 128, allowNull: true),
                NewDataColumn<string>("PaymentOrganisationIdentifier", 32, true),
                NewDataColumn<string>("PaymentOrganisationName", 256, true),
                NewDataColumn<bool>("IsIndicative", defaultValue: true),
                NewDataColumn<string>("TrustStatus", 256, allowNull: true),
                NewDataColumn<string>("UPIN", 32, allowNull: true),
                NewDataColumn<string>("EstablishmentNumber", 256, allowNull: true),
                NewDataColumn<string>("DfeEstablishmentNumber", 256, allowNull: true),
                NewDataColumn<string>("ProviderProfileIdType", 256, allowNull: true),
                NewDataColumn<string>("NavVendorNo", 256, allowNull: true),
                NewDataColumn<string>("CrmAccountId", 256, allowNull: true),
                NewDataColumn<string>("LegalName", 256, allowNull: true),
                NewDataColumn<string>("PhaseOfEducation", 256, allowNull: true),
                NewDataColumn<string>("ReasonEstablishmentOpened", 256, allowNull: true),
                NewDataColumn<string>("ReasonEstablishmentClosed", 256, allowNull: true),
                NewDataColumn<string>("Predecessors", 256, allowNull: true),
                NewDataColumn<string>("Town", 256, allowNull: true),
                NewDataColumn<string>("Postcode", 256, allowNull: true),
                NewDataColumn<string>("CompaniesHouseNumber", 256, allowNull: true),
                NewDataColumn<string>("GroupIdNumber", 256, allowNull: true),
                NewDataColumn<string>("RscRegionName", 256, allowNull: true),
                NewDataColumn<string>("RscRegionCode", 256, allowNull: true),
                NewDataColumn<string>("GovernmentOfficeRegionName", 256, allowNull: true),
                NewDataColumn<string>("GovernmentOfficeRegionCode", 256, allowNull: true),
                NewDataColumn<string>("DistrictName", 256, allowNull: true),
                NewDataColumn<string>("DistrictCode", 256, allowNull: true),
                NewDataColumn<string>("WardName", 256, allowNull: true),
                NewDataColumn<string>("WardCode", 256, allowNull: true),
                NewDataColumn<string>("CensusWardName", 256, allowNull: true),
                NewDataColumn<string>("CensusWardCode", 256, allowNull: true),
                NewDataColumn<string>("MiddleSuperOutputAreaName", 256, allowNull: true),
                NewDataColumn<string>("MiddleSuperOutputAreaCode", 256, allowNull: true),
                NewDataColumn<string>("LowerSuperOutputAreaName", 256, allowNull: true),
                NewDataColumn<string>("LowerSuperOutputAreaCode", 256, allowNull: true),
                NewDataColumn<string>("ParliamentaryConstituencyName", 256, allowNull: true),
                NewDataColumn<string>("ParliamentaryConstituencyCode", 256, allowNull: true),
                NewDataColumn<string>("LondonRegionCode", 256, allowNull: true),
                NewDataColumn<string>("LondonRegionName", 256, allowNull: true),
                NewDataColumn<string>("CountryCode", 256, allowNull: true),
                NewDataColumn<string>("CountryName", 256, allowNull: true),
                NewDataColumn<string>("LocalGovernmentGroupTypeCode", 256, allowNull: true),
                NewDataColumn<string>("LocalGovernmentGroupTypeName", 256, allowNull: true),
                NewDataColumn<string>("Street", 256, allowNull: true),
                NewDataColumn<string>("Locality", 256, allowNull: true),
                NewDataColumn<string>("Address3", 256, allowNull: true),
                NewDataColumn<string>("ProviderTypeCode", 256, allowNull: true),
                NewDataColumn<string>("ProviderSubTypeCode", 256, allowNull: true),
                NewDataColumn<string>("PreviousLaCode", 256, allowNull: true),
                NewDataColumn<string>("PreviousLaName", 256, allowNull: true),
                NewDataColumn<string>("PreviousEstablishmentNumber", 256, allowNull: true),
                NewDataColumn<string>("FurtherEducationTypeCode", 256, allowNull: true),
                NewDataColumn<string>("FurtherEducationTypeName", 256, allowNull: true)
            };

        protected override void AddDataRowToDataTable(PublishedProviderVersion dto)
        {
            Provider provider = dto.Provider;

            DataTable.Rows.Add(dto.PublishedProviderId,
                dto.ProviderId,
                provider.Name,
                provider.UKPRN,
                DbNullSafe(provider.URN),
                DbNullSafe(provider.Authority),
                provider.ProviderType,
                provider.ProviderSubType,
                DbNullSafe(provider.DateOpened?.UtcDateTime),
                DbNullSafe(provider.DateClosed?.UtcDateTime),
                DbNullSafe(provider.LACode),
                DbNullSafe(provider.Status),
                DbNullSafe(provider.GetSuccessors().JoinWith(';')),
                DbNullSafe(provider.TrustCode),
                DbNullSafe(provider.TrustName),
                DbNullSafe(provider.PaymentOrganisationIdentifier),
                DbNullSafe(provider.PaymentOrganisationName),
                dto.IsIndicative,
                DbNullSafe(provider.TrustStatus),
                DbNullSafe(provider.UPIN),
                DbNullSafe(provider.EstablishmentNumber),
                DbNullSafe(provider.DfeEstablishmentNumber),
                DbNullSafe(provider.ProviderProfileIdType),
                DbNullSafe(provider.NavVendorNo),
                DbNullSafe(provider.CrmAccountId),
                DbNullSafe(provider.LegalName),
                DbNullSafe(provider.PhaseOfEducation),
                DbNullSafe(provider.ReasonEstablishmentOpened),
                DbNullSafe(provider.ReasonEstablishmentClosed),
                DbNullSafe(provider.Predecessors?.JoinWith(';')),
                DbNullSafe(provider.Town),
                DbNullSafe(provider.Postcode),
                DbNullSafe(provider.CompaniesHouseNumber),
                DbNullSafe(provider.GroupIdNumber),
                DbNullSafe(provider.RscRegionName),
                DbNullSafe(provider.RscRegionCode),
                DbNullSafe(provider.GovernmentOfficeRegionName),
                DbNullSafe(provider.GovernmentOfficeRegionCode),
                DbNullSafe(provider.DistrictName),
                DbNullSafe(provider.DistrictCode),
                DbNullSafe(provider.WardName),
                DbNullSafe(provider.WardCode),
                DbNullSafe(provider.CensusWardName),
                DbNullSafe(provider.CensusWardCode),
                DbNullSafe(provider.MiddleSuperOutputAreaName),
                DbNullSafe(provider.MiddleSuperOutputAreaCode),
                DbNullSafe(provider.LowerSuperOutputAreaName),
                DbNullSafe(provider.LowerSuperOutputAreaCode),
                DbNullSafe(provider.ParliamentaryConstituencyName),
                DbNullSafe(provider.ParliamentaryConstituencyCode),
                DbNullSafe(provider.LondonRegionCode),
                DbNullSafe(provider.LondonRegionName),
                DbNullSafe(provider.CountryCode),
                DbNullSafe(provider.CountryName),
                DbNullSafe(provider.LocalGovernmentGroupTypeCode),
                DbNullSafe(provider.LocalGovernmentGroupTypeName),
                DbNullSafe(provider.Street),
                DbNullSafe(provider.Locality),
                DbNullSafe(provider.Address3),
                DbNullSafe(provider.ProviderTypeCode),
                DbNullSafe(provider.ProviderSubTypeCode),
                DbNullSafe(provider.PreviousLaCode),
                DbNullSafe(provider.PreviousLaName),
                DbNullSafe(provider.PreviousEstablishmentNumber),
                DbNullSafe(provider.FurtherEducationTypeCode),
                DbNullSafe(provider.FurtherEducationTypeName));
        }

        protected override void EnsureTableNameIsSet(PublishedProviderVersion dto)
            => TableName = $"[dbo].[{dto.FundingStreamId}_{dto.FundingPeriodId}_Providers]";
    }
}