name: $(Rev:r)

pool:
  vmImage: windows-2019

resources:
  repositories:
  - repository: self

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  system.debug: false

steps:
 - task: UseDotNet@2
   displayName: 'Use .NET Core sdk ${{ parameters.DotnetCoreSdkVersion }}'
   inputs:
     version: ${{ parameters.DotnetCoreSdkVersion }}

 - task: DotNetCoreCLI@2
   displayName: 'dotnet restore'
   inputs:
     command: restore
     vstsFeed: 'ecf37bc0-472b-47bf-91e3-6774809fd194'
     projects: 'CalculateFunding-Backend.sln'

 - task: DotNetCoreCLI@2
   displayName: 'dotnet test'
   inputs:
     command: test
     arguments: '--configuration Release /p:AssemblyVersion=$(Build.BuildNumber) --collect "Code coverage"'
     projects: |
     **/*.Functions.*UnitTests/*.csproj
     **/*.Services.*Tests/*.csproj
     **/*.Models.*Tests/*.csproj
     **/*.*AcceptanceTests/*.csproj
     **/*.Api.*Tests/*.csproj
     **/*.Generators.*Tests/*.csproj

 - task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    publishWebProjects: false
    zipAfterPublish: false
    projects: |
     **/*.Api.*.csproj
     **/*.Functions.*.csproj
    arguments: '--configuration Release /p:AssemblyVersion=$(Build.BuildNumber)'
     