name: $(Rev:r)

pool:
  vmImage: windows-2022

trigger:
  branches:
    include:
    - master
    - providers
    - fdps
  paths:
    include:
    - CalculateFunding.Api.External
    - CalculateFunding.Functions.External
    - CalculateFunding.Services.External
    - CalculateFunding.Services.External.UnitTests
    - CalculateFunding.Services.Core
    - CalculateFunding.Api.External.UnitTests
    - DevOps/search-indexers/publishedfundingindexer
    - DevOps/search-indexes/publishedfundingindex
    - CalculateFunding.Models.Publishing
    - CalculateFunding.Services.Publishing
    - CalculateFunding.Models.Search

variables:
 - name: ProjectName
   value: 'external'
 - name: ServiceName
   value: 'external'
 - name: releaseconfiguration
   value: 'release'
 - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
   value: true
 - name: DOTNET_CLI_TELEMETRY_OPTOUT 
   value: true
 - name: BuildApi
   value: true
 - name: BuildFunction
   value: false
 - name: SecureSmokeTest
   value: true
 - group: 'Dotnet Core SDK Version'
 - group: 'Azure Settings Integration-v2'
 - group: 'Integration Tests Info - Integration-PR' 
 - group: 'Integration Tests KV - Integration-PR'
 - group: 'Shared Infrastructure - Integration - v2'
 - group: 'Resource Tags test-v2 integration-v2'
 - group: 'Feature Toggles Integration-v2'


steps:
 - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
   - template: templates\standard-service-arm-deploy.yml
     parameters:
       ServiceName: ${{ variables.ServiceName }}
       ResourceGroup: $(ResourceGroup)
       azureSubscription: $(azureSubscription)
       overrideParameters: '-environmentTag "$(environmentTag)" -parentBusinessTag "$(parentBusinessTag)" -portfolioTag "$(portfolioTag)" -productTag "$(productTag)" -serviceLineTag "$(serviceLineTag)" -environmentKey "$(EnvironmentKey)" -productVersion "pr" -appServiceLogRetentionDays "0" -sendWebLogsToStorage "false" -apiHostingPlanName $(apiHostingPlanNamePR) -keyVaultName $(keyVaultNamePR) -sharedLogStorageName $(sharedLogStorageName) -searchName $(searchName) -azureAdTenantId $(AzureAdTenantId) -azureAdAudienceExternal $(AzureAdAudienceExternal) -Http5xxTH "100" -Http401TH "100" -HttpResponseTimeTH "100" -applicationInsightsName $(applicationInsightsName) -addCerttoExternalAppService "false" -externalApiCertificateThumbprint "not-applicable" -externalApiCertName "not-applicable" -externalApiHostName "not-applicable" -providerProfilingApiUrl $(providerProfilingClientApiEndpoint) -providerProfilingAzureBearerTokenClientId $(providerProfilingAzureBearerTokenOptionsClientId) -providerProfilingAzureBearerTokenGrantType "client_credentials" -providerProfilingAzureBearerTokenScope $(providerProfilingAzureBearerTokenOptionsScope) -providerProfilingAzureBearerTokenUrl $(providerProfilingAzureBearerTokenOptionsUrl)'

 - template: templates\standard-service-pr-ci-build-prinfra-noModelsTests.yml
   parameters:
     ProjectName: ${{ variables.ProjectName }}
     ServiceName: ${{ variables.ServiceName }} 
     DotnetCoreSdkVersion: $(DotnetCoreSdkVersionNet6)
     ApiFrameworkVersion: 'net6'
     ResourceGroup: $(ResourceGroup)
     ServiceBusSettings: $(ServiceBusSettingsPR)
     azureSubscription: '$(azureSubscription)'
     environmentKey: $(EnvironmentKey)
     BuildApi: ${{ variables.BuildApi }}
     BuildFunction: ${{ variables.BuildFunction }}
     SecureSmokeTest: ${{ variables.SecureSmokeTest }}
     SmokeTestTenantId: $(SmokeTestTenantId)
     SmokeTestApplicationUrl: $(SmokeTestApplicationUrl-external)
     SmokeTestClientID: $(SmokeTestClientId-external)
     SmokeTestClientSecret: $(ExternalAzureAdClientSecret)

 - task: DotNetCoreCLI@2
   condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'), eq(variables.runIntegrationTests, true))
   displayName: 'dotnet test for Integration tests'
   inputs:
     command: 'test'
     projects: |
      **/*Api.${{ variables.ProjectName }}.IntegrationTests/*.csproj
     arguments: '--configuration Release /p:AssemblyVersion=$(Build.BuildNumber)'
   env:
     AzureAd:Audience: $(AzureAdAudienceExternal) 
     AzureAd:Authority: $(AzureAdAuthority)
     AzureAd:TenantId: $(AzureAdTenantId)
     AzureConfiguration:ConnectionString: $(AzureConfigurationConnectionString)
     AzureStorageSettings:ConnectionString: $(AzureStorageSettings)
     CommonStorageSettings:ConnectionString: $(AzureStorageSettings)
     CosmosDbSettings:ConnectionString: $(CosmosDbSettings)
     CosmosDbSettings:ContainerName: 'publishedfunding'
     CosmosDbSettings:DatabaseName: $(CosmosDbSettingsDatabaseName)
     RedisSettings:CacheConnection: $(RedisSettings)
     ResourceGroup: $(ResourceGroup)
     SearchServiceKey: $(SearchServiceKey)
     SearchServiceName: $(SearchServiceName)
     ServiceBusSettings:ConnectionString: $(ServiceBusSettingsPR)
     storageConfiguration:ConnectionString: $(AzureStorageSettings)
     WEBSITE_HTTPLOGGING_CONTAINER_URL: $(WEBSITE_HTTPLOGGING_CONTAINER_URL)
     apiKeyMiddleware:apiKey: $(svcapiexternal)
     cfsClient:ApiEndpoint: $(cfsClientApiEndpoint)
     policiesClient:ApiEndpoint: $(policiesClientApiEndpoint)
     policiesClient:ApiKey: $(svcapipolicy)
     providerProfilingAzureBearerTokenOptions:ClientId: $(providerProfilingAzureBearerTokenOptionsClientId) 
     providerProfilingAzureBearerTokenOptions:ClientSecret: $(providerProfilingAzureBearerTokenClientSecret)
     providerProfilingAzureBearerTokenOptions:GrantType : 'client_credentials'
     providerProfilingAzureBearerTokenOptions:Scope: $(providerProfilingAzureBearerTokenOptionsScope)
     providerProfilingAzureBearerTokenOptions:Url: $(providerProfilingAzureBearerTokenOptionsUrl)
     providerProfilingClient:ApiEndpoint: $(providerProfilingClientApiEndpoint)
     providerProfilingClient:ApiKey: $(svcapiprofiling)
     providersClient:ApiEndpoint: $(providersClientApiEndpoint)
     providersClient:ApiKey: $(svcapiproviders)


 - task: AzureCLI@2
   condition: and(failed(), eq( '${{ variables.BuildApi }}', true), eq(variables['Build.Reason'], 'PullRequest'))
   displayName: 'Reset in-progress swap on failure'
   inputs:
     azureSubscription: $(azureSubscription)
     scriptType: pscore
     scriptLocation: inlineScript
     inlineScript: 'az webapp deployment slot swap --action reset --slot Staging --name app-$(EnvironmentKey)-${{ variables.ServiceName }}-pr --resource-group $(ResourceGroup)'