name: $(Rev:r)

pool:
  vmImage: windows-2019

trigger:
  batch: true
  branches:
    include:
    - master
    - providers
    - fdps
  paths:
    include:
    - CalculateFunding.Services.Core
    - CalculateFunding.Services.Core.AspNet
    - CalculateFunding.Services.Graph
    - CalculateFunding.Models.Users
    - CalculateFunding.Repositories.Common.Search
    - CalculateFunding.Api.Graph
    - CalculateFunding.Api.Graph.UnitTests

variables:
 - name: ProjectName
   value: 'graph'
 - name: ServiceName
   value: 'graph'
 - name: releaseconfiguration
   value: 'release'
 - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
   value: true
 - name: DOTNET_CLI_TELEMETRY_OPTOUT 
   value: true
 - name: BuildApi
   value: true
 - name: BuildFunction
   value: false
 - name: SecureSmokeTest
   value: false
 - group: 'Dotnet Core SDK Version'
 - group: 'Azure Settings Integration-v2'
 - group: 'Smoke Test Info - Integration-v2' 
 - group: 'Smoke Test KV - Integration-v2'

steps:
 - template: templates\standard-service-pr-ci-build.yml
   parameters:
     ProjectName: ${{ variables.ProjectName }}
     ServiceName: ${{ variables.ServiceName }} 
     DotnetCoreSdkVersion: $(DotnetCoreSdkVersion)
     ResourceGroup: $(ResourceGroup)
     BuildApi: ${{ variables.BuildApi }}
     BuildFunction: ${{ variables.BuildFunction }}
     SecureSmokeTest: ${{ variables.SecureSmokeTest }}
     APIKey: $(svcapigraph)

 - task: DotNetCoreCLI@2
   condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'), eq(variables.runIntegrationTests, true))
   displayName: 'dotnet test for Integration tests'
   inputs:
     command: 'test'
     projects: |
      **/*Api.${{ variables.ProjectName }}.IntegrationTests/*.csproj
     arguments: '--configuration Release /p:AssemblyVersion=$(Build.BuildNumber)'
   env:
     AzureConfiguration:ConnectionString: $(AzureConfigurationConnectionString)
     AzureStorageSettings:ConnectionString: $(AzureStorageSettings)
     CommonStorageSettings:ConnectionString: $(AzureStorageSettings)
     RedisSettings:CacheConnection: $(RedisSettings)
     ResourceGroup: $(ResourceGroup)
     ServiceBusSettings:ConnectionString: $(ServiceBusSettings)
     storageConfiguration:ConnectionString: $(AzureStorageSettings)
     WEBSITE_HTTPLOGGING_CONTAINER_URL: $(WEBSITE_HTTPLOGGING_CONTAINER_URL)
     apiKeyMiddleware:apiKey: $(svcapigraph)
     cfsClient:ApiEndpoint: $(cfsClientApiEndpoint)
     graphClient:ApiEndpoint: $(graphClientApiEndpoint)
     graphClient:ApiKey: $(svcapigraph)
     CosmosGraphSettings:ApiKey: $(graphCosmosDbSettingsAuthKey)
     CosmosGraphSettings:ContainerPath: '/dbs/cfs-t1in-gph-db/colls/specs'
     CosmosGraphSettings:EndPointUrl: $(CosmosGraphSettingsEndPointUrl)
     CosmosGraphSettings:Port: '443'