name: $(Rev:r)

pool:
  vmImage: windows-2019

trigger: none

variables:
 - name: ProjectName
   value: 'external'
 - name: ServiceName
   value: 'external'
 - name: releaseconfiguration
   value: 'release'
 - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
   value: true
 - name: DOTNET_CLI_TELEMETRY_OPTOUT 
   value: true
 - name: BuildApi
   value: true
 - name: BuildFunction
   value: false
 - name: SecureSmokeTest
   value: true
 - group: 'Dotnet Core SDK Version'
 - group: 'Smoke Test Info - Integration-v2' 
 - group: 'Smoke Test KV - Integration-v2'


steps:
  - template: templates\standard-service-pr-build.yml
    parameters:
      ProjectName: ${{ variables.ProjectName }}
      ServiceName: ${{ variables.ServiceName }} 
      DotnetCoreSdkVersion: $(DotnetCoreSdkVersion)
      ResourceGroup: $(ResourceGroup)
      BuildApi: ${{ variables.BuildApi }}
      BuildFunction: ${{ variables.BuildFunction }}
      SecureSmokeTest: ${{ variables.SecureSmokeTest }}
      SmokeTestTenantId: $(SmokeTestTenantId)
      SmokeTestApplicationUrl: $(SmokeTestApplicationUrl-external)
      SmokeTestClientID: $(SmokeTestClientId-external)
      SmokeTestClientSecret: $(ExternalAzureAdClientSecret)
  
