name: $(Rev:r)

pool:
  vmImage: windows-2019

trigger:
  branches:
    include:
    - master
    - providers
    - fdps
  paths:
    include:
    - CalculateFunding.Api.Policy
    - CalculateFunding.Functions.Policy
    - CalculateFunding.Services.Policy
    - CalculateFunding.Services.Core
    - CalculateFunding.Models.Policy
    - CalculateFunding.Api.Policy.UnitTests
    - CalculateFunding.Functions.Policy.UnitTests
    - CalculateFunding.Services.Policy.UnitTests

variables:
 - name: ProjectName
   value: 'policy'
 - name: ServiceName
   value: 'policy'
 - name: releaseconfiguration
   value: 'release'
 - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
   value: true
 - name: DOTNET_CLI_TELEMETRY_OPTOUT 
   value: true
 - name: BuildApi
   value: true
 - name: BuildFunction
   value: true
 - name: SecureSmokeTest
   value: false
 - group: 'Dotnet Core SDK Version'
 - group: 'Azure Settings Integration-v2'
 - group: 'Smoke Test Info - Integration-v2'
 - group: 'Smoke Test KV - Integration-v2'

steps:
- template: templates\standard-service-pr-ci-build.yml
  parameters:
     ProjectName: ${{ variables.ProjectName }}
     ServiceName: ${{ variables.ServiceName }} 
     DotnetCoreSdkVersion: $(DotnetCoreSdkVersion)
     ResourceGroup: $(ResourceGroup)
     BuildApi: ${{ variables.BuildApi }}
     BuildFunction: ${{ variables.BuildFunction }}
     SecureSmokeTest: ${{ variables.SecureSmokeTest }}
     APIKey: $(svcapipolicy)

- task: DotNetCoreCLI@2
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'), eq(variables.runIntegrationTests, true))
  displayName: 'dotnet test for Integration tests'
  inputs:
    command: 'test'
    projects: |
     **/*Api.${{ variables.ProjectName }}.IntegrationTests/*.csproj
    arguments: '--configuration Release /p:AssemblyVersion=$(Build.BuildNumber)'
  env:
     AzureConfiguration:ConnectionString: $(AzureConfigurationConnectionString)
     AzureSignalRConnectionString: $(AzureSignalRConnectionString)
     AzureStorageSettings:ConnectionString: $(AzureStorageSettings)
     CommonStorageSettings:ConnectionString: $(AzureStorageSettings)
     CosmosDbSettings:ConnectionString: $(CosmosDbSettings)
     CosmosDbSettings:ContainerName: 'policy'
     CosmosDbSettings:DatabaseName: $(CosmosDbSettingsDatabaseName)
     RedisSettings:CacheConnection: $(RedisSettings)
     ResourceGroup: $(ResourceGroup)
     SearchServiceKey: $(SearchServiceKey)
     SearchServiceName: $(SearchServiceName)
     ServiceBusSettings:ConnectionString: $(ServiceBusSettings)
     storageConfiguration:ConnectionString: $(AzureStorageSettings)
     WEBSITE_HTTPLOGGING_CONTAINER_URL: $(WEBSITE_HTTPLOGGING_CONTAINER_URL)
     apiKeyMiddleware:apiKey: $(svcapipolicy)
     cfsClient:ApiEndpoint: $(cfsClientApiEndpoint)
     calcsClient:ApiEndpoint: $(calcsClientApiEndpoint)
     calcsClient:ApiKey: $(svcapicalcs)
     jobsClient:ApiEndpoint: $(jobsClientApiEndpoint)
     jobsClient:ApiKey: $(svcapijobs)
     policiesClient:ApiEndpoint: $(policiesClientApiEndpoint)
     policiesClient:ApiKey: $(svcapipolicy)
     resultsClient:ApiEndpoint: $(resultsClientApiEndpoint)
     resultsClient:ApiKey: $(svcapiresults)
     specificationsClient:ApiEndpoint: $(specificationsClientApiEndpoint)
     specificationsClient:ApiKey: $(svcapispecs)