name: $(Rev:r)

pool:
  vmImage: windows-2019

trigger:
  branches:
    include:
    - master
    - providers
  paths:
    include:
    - CalculateFunding.Api.FundingDataZone
    - CalculateFunding.Functions.FundingDataZone
    - CalculateFunding.Services.FundingDataZone
    - CalculateFunding.Models.FundingDataZone

variables:
 - name: ProjectName
   value: 'FundingDataZone'
 - name: ServiceName
   value: 'fdz'
 - name: releaseconfiguration
   value: 'release'
 - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
   value: true
 - name: DOTNET_CLI_TELEMETRY_OPTOUT 
   value: true
 - name: BuildApi
   value: true
 - name: BuildFunction
   value: true
 - name: SecureSmokeTest
   value: false
 - group: 'Dotnet Core SDK Version'
 - group: 'Azure Settings Integration-v2'
 - group: 'Smoke Test Info - Integration-v2' 
 - group: 'Smoke Test KV - Integration-v2'

steps:
 - template: templates\standard-service-pr-ci-build.yml
   parameters:
     ProjectName: ${{ variables.ProjectName }}
     ServiceName: ${{ variables.ServiceName }} 
     DotnetCoreSdkVersion: $(DotnetCoreSdkVersion)
     ResourceGroup: $(ResourceGroup)
     BuildApi: ${{ variables.BuildApi }}
     BuildFunction: ${{ variables.BuildFunction }}
     SecureSmokeTest: ${{ variables.SecureSmokeTest }}
     APIKey: $(svcapifdz)

 - task: DotNetCoreCLI@2
   condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'), eq(variables.runIntegrationTests, true))
   displayName: 'dotnet test for Integration tests'
   inputs:
     command: 'test'
     projects: |
      **/*Api.${{ variables.ProjectName }}.IntegrationTests/*.csproj
     arguments: '--configuration Release /p:AssemblyVersion=$(Build.BuildNumber)'
   env:
     AzureConfiguration:ConnectionString: $(AzureConfigurationConnectionString)
     AzureStorageSettings:ConnectionString: $(AzureStorageSettings)
     CommonStorageSettings:ConnectionString: $(AzureStorageSettings)
     RedisSettings:CacheConnection: $(RedisSettings)
     ResourceGroup: $(ResourceGroup)
     ServiceBusSettings:ConnectionString: $(ServiceBusSettings)
     storageConfiguration:ConnectionString: $(AzureStorageSettings)
     WEBSITE_HTTPLOGGING_CONTAINER_URL: $(WEBSITE_HTTPLOGGING_CONTAINER_URL)
     FDZSqlStorageSettings:ConnectionString: $(fdzSqlReadOnlyConnection)
     apiKeyMiddleware:apiKey: $(svcapifdz)
     cfsClient:ApiEndpoint: $(cfsClientApiEndpoint)
     fdzClient:ApiEndpoint: $(fdzClientApiEndpoint)
     fdzClient:ApiKey: $(svcapifdz)
     jobsClient:ApiEndpoint: $(jobsClientApiEndpoint)
     jobsClient:ApiKey: $(svcapijobs)
     providersClient:ApiEndpoint: $(providersClientApiEndpoint)
     providersClient:ApiKey: $(svcapiproviders)