name: $(Rev:r)

pool:
  vmImage: windows-2019

trigger:
  branches:
    include:
    - providers
    - fdps
  paths:
    include:
    - CalculateFunding.Api.Publishing
    - CalculateFunding.Functions.Publishing
    - CalculateFunding.Services.Publishing
    - CalculateFunding.Services.Publishing.UnitTests
    - CalculateFunding.Services.Core
    - Devops/search-indexes/publishedfundingindex
    - Devops/search-indexes/publishedproviderindex
    - CalculateFunding.Generators.Schema10
    - CalculateFunding.Generators
    - CalculateFunding.Models.Search
    - CalculateFunding.Models.Versioning
    - CalculateFunding.Models.ProviderLegacy
    - CalculateFunding.Models.Publishing
    - CalculateFunding.Models.External

variables:
 - name: ProjectName
   value: 'publishing'
 - name: ServiceName
   value: 'publishing'
 - name: releaseconfiguration
   value: 'release'
 - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
   value: true
 - name: DOTNET_CLI_TELEMETRY_OPTOUT 
   value: true
 - name: BuildApi
   value: true
 - name: BuildFunction
   value: true
 - name: SecureSmokeTest
   value: false
 - group: 'Dotnet Core SDK Version'
 - group: 'Azure Settings Integration-v2'
 - group: 'Smoke Test Info - Integration-v2' 
 - group: 'Smoke Test KV - Integration-v2'

steps:
 - template: templates\standard-service-pr-ci-build.yml
   parameters:
     ProjectName: ${{ variables.ProjectName }}
     ServiceName: ${{ variables.ServiceName }} 
     DotnetCoreSdkVersion: $(DotnetCoreSdkVersion)
     ResourceGroup: $(ResourceGroup)
     BuildApi: ${{ variables.BuildApi }}
     BuildFunction: ${{ variables.BuildFunction }}
     SecureSmokeTest: ${{ variables.SecureSmokeTest }}
     APIKey: $(svcapipublishing)

 - task: DotNetCoreCLI@2
   condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'), eq(variables.runIntegrationTests, true))
   displayName: 'dotnet test for Integration tests'
   inputs:
     command: 'test'
     projects: |
      **/*Api.${{ variables.ProjectName }}.IntegrationTests/*.csproj
     arguments: '--configuration Release /p:AssemblyVersion=$(Build.BuildNumber)'
   env:
     AzureConfiguration:ConnectionString: $(AzureConfigurationConnectionString)
     AzureStorageSettings:ConnectionString: $(AzureStorageSettings)
     CommonStorageSettings:ConnectionString: $(AzureStorageSettings)
     CosmosDbSettings:ConnectionString: $(CosmosDbSettings)
     CosmosDbSettings:ContainerName: 'publishing'
     CosmosDbSettings:DatabaseName: $(CosmosDbSettingsDatabaseName)
     RedisSettings:CacheConnection: $(RedisSettings)
     ResourceGroup: $(ResourceGroup)
     SearchServiceKey: $(SearchServiceKey)
     SearchServiceName: $(SearchServiceName)
     ServiceBusSettings:ConnectionString: $(ServiceBusSettings)
     storageConfiguration:ConnectionString: $(AzureStorageSettings)
     WEBSITE_HTTPLOGGING_CONTAINER_URL: $(WEBSITE_HTTPLOGGING_CONTAINER_URL)
     saSql:ConnectionString: $(QADatabaseWriterConnectionString)
     apiKeyMiddleware:apiKey: $(svcapipublishing)
     cfsClient:ApiEndpoint: $(cfsClientApiEndpoint)
     calcsClient:ApiEndpoint: $(calcsClientApiEndpoint)
     calcsClient:ApiKey: $(svcapicalcs)
     fdzClient:ApiEndpoint: $(fdzClientApiEndpoint)
     fdzClient:ApiKey: $(svcapifdz)
     jobsClient:ApiEndpoint: $(jobsClientApiEndpoint)
     jobsClient:ApiKey: $(svcapijobs)
     policiesClient:ApiEndpoint: $(policiesClientApiEndpoint)
     policiesClient:ApiKey: $(svcapipolicy)
     providerProfilingAzureBearerTokenOptions:ClientId: $(providerProfilingAzureBearerTokenOptionsClientId) 
     providerProfilingAzureBearerTokenOptions:ClientSecret: $(providerProfilingAzureBearerTokenClientSecret)
     providerProfilingAzureBearerTokenOptions:GrantType : 'client_credentials'
     providerProfilingAzureBearerTokenOptions:Scope: $(providerProfilingAzureBearerTokenOptionsScope)
     providerProfilingAzureBearerTokenOptions:Url: $(providerProfilingAzureBearerTokenOptionsUrl)
     providerProfilingClient:ApiEndpoint: $(providerProfilingClientApiEndpoint)
     providerProfilingClient:ApiKey: $(svcapiprofiling)
     providersClient:ApiEndpoint: $(providersClientApiEndpoint)
     providersClient:ApiKey: $(svcapiproviders)
     specificationsClient:ApiEndpoint: $(specificationsClientApiEndpoint)
     specificationsClient:ApiKey: $(svcapispecs)