name: $(Rev:r)

pool:
  vmImage: windows-2019

resources:
  repositories:
  - repository: self
  - repository: funding-blocks
    type: github
    name: SkillsFundingAgency/funding-platform-building-blocks
    ref: refs/heads/master
    endpoint: 'Github (ESFA)'

variables:
 - name: releaseconfiguration
   value: 'release'
 - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
   value: true
 - name: DOTNET_CLI_TELEMETRY_OPTOUT 
   value: true
 - group: 'DotnetCoreSDKVersion'

steps:
  - template: azure-pipelines-templates/cfs/standard-service-build.yml@funding-blocks
    parameters:
      DotNetCoreVersion: ${{ variables.DotnetCoreSdkVersion }}
      releaseconfiguration: ${{ variables.releaseconfiguration }}
      ProjectName: CalcEngine