name: $(Rev:r)

pool:
  vmImage: windows-2019

resources:
  repositories:
  - repository: self

trigger:
  branches:
    include:
    - master
    - providers
    - fdps
  paths:
    include:
    - CalculateFunding.Api.Profiling
    - CalculateFunding.Functions.Profiling
    - CalculateFunding.Services.Profiling
    - CalculateFunding.Services.Core
    - CalculateFunding.Api.Profiling.UnitTests
    - CalculateFunding.Services.Profiling.UnitTests
    - CalculateFunding.Profiling.GWTs

variables:
 - name: ProjectName
   value: 'profiling'
 - name: ServiceName
   value: 'profiling'
 - name: releaseconfiguration
   value: 'release'
 - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
   value: true
 - name: DOTNET_CLI_TELEMETRY_OPTOUT 
   value: true
 - name: BuildApi
   value: true
 - name: BuildFunction
   value: false
 - name: SecureSmokeTest
   value: true
 - group: 'Dotnet Core SDK Version'
 - group: 'Azure Settings Integration-v2'
 - group: 'Smoke Test Info - Integration-v2' 
 - group: 'Smoke Test KV - Integration-v2'


steps:
 - template: templates\standard-service-pr-ci-build.yml
   parameters:
     ProjectName: ${{ variables.ProjectName }}
     ServiceName: ${{ variables.ServiceName }} 
     DotnetCoreSdkVersion: $(DotnetCoreSdkVersion)
     ResourceGroup: $(ResourceGroup)
     BuildApi: ${{ variables.BuildApi }}
     BuildFunction: ${{ variables.BuildFunction }}
     SecureSmokeTest: ${{ variables.SecureSmokeTest }}
     SmokeTestTenantId: $(SmokeTestTenantId)
     SmokeTestApplicationUrl: $(SmokeTestApplicationUrl-profiling)
     SmokeTestClientID: $(SmokeTestClientId-profiling)
     SmokeTestClientSecret: $(ProfilingAzureAdClientSecret)

 - task: DotNetCoreCLI@2
   condition: and(succeeded(), eq(variables.runIntegrationTests, true))
   displayName: 'dotnet test for Integration tests'
   inputs:
     command: 'test'
     projects: |
       **/*Api.Profiling.IntegrationTests/*.csproj
     arguments: '--configuration Release /p:AssemblyVersion=$(Build.BuildNumber)'
   env:
     AzureAd:Audience: $(AzureAdAudienceprofiling) 
     AzureAd:Authority: $(AzureAdAuthority)
     AzureAd:TenantId: $(AzureAdTenantId)
     AzureConfiguration:ConnectionString: $(AzureConfigurationConnectionString)
     AzureStorageSettings:ConnectionString: $(AzureStorageSettings)
     CosmosDbSettings:ConnectionString: $(CosmosDbSettings)
     CosmosDbSettings:ContainerName: 'profiling'
     CosmosDbSettings:DatabaseName: $(CosmosDbSettingsDatabaseName)
     RedisSettings:CacheConnection: $(RedisSettings)
     ResourceGroup: $(ResourceGroup)
     ServiceBusSettings:ConnectionString: $(ServiceBusSettings)
     storageConfiguration:ConnectionString: $(AzureStorageSettings)
     cfsClient:ApiEndpoint: $(cfsClientApiEndpoint)
     providerProfilingClient:ApiEndpoint: $(providerProfilingClientApiEndpoint)
     providerProfilingClient:ApiKey: $(svcapiprofiling)
     ProfilingAzureAdClientID: $(SmokeTestClientId-profiling)
     ProfilingAzureAdClientSecret: $(ProfilingAzureAdClientSecret)