name: $(Rev:r)

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: self

variables:
 - name: system.debug
   value: 'true'

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    verbose: false
    customCommand: build