using System.Text;
using CalculateFunding.Api.External.V1.Models;
using Newtonsoft.Json;
using Swashbuckle.AspNetCore.Examples;

namespace CalculateFunding.Api.External.V1.Controllers
{
    public class LocalAuthorityResultSummaryExamples : IExamplesProvider
    {
        public object GetExamples()
        {
            string sampleData = GetSampleData();

            LocalAuthorityResultsSummary summary = JsonConvert.DeserializeObject<LocalAuthorityResultsSummary>(sampleData);

            return summary;
        }

        public string GetSampleData()
        {
            var sb = new StringBuilder();

            sb.AppendLine(@"{");
            sb.AppendLine(@"	""FundingPeriod"": ""2017-2018"",");
            sb.AppendLine(@"	""LocalAuthorities"": [");
            sb.AppendLine(@"		{");
            sb.AppendLine(@"			""LANo"": ""46"",");
            sb.AppendLine(@"			""LAName"": ""Wirral"",");
            sb.AppendLine(@"			""Providers"": [");
            sb.AppendLine(@"				{");
            sb.AppendLine(@"					""Ukprn"": ""105019"",");
            sb.AppendLine(@"					""LAEStab"": ""3442216"",");
            sb.AppendLine(@"					""OrganisationName"": ""Mill Park Infant School"",");
            sb.AppendLine(@"					""OrganisationType"": ""School"",");
            sb.AppendLine(@"					""OrganisationSubType"": ""Community"",");
            sb.AppendLine(@"					""EligiblePupils"": 0,");
            sb.AppendLine(@"					""AllocationValue"": 1193998.0,");
            sb.AppendLine(@"					""FundingPeriods"": [");
            sb.AppendLine(@"						{");
            sb.AppendLine(@"							""FundingPeriod"": {");
            sb.AppendLine(@"								""PeriodType"": ""AY"",");
            sb.AppendLine(@"								""PeriodId"": ""AY2017181"",");
            sb.AppendLine(@"								""StartDate"": ""2017-08-31T23:00:00+00:00"",");
            sb.AppendLine(@"								""EndDate"": ""2018-08-30T23:00:00+00:00""");
            sb.AppendLine(@"							},");
            sb.AppendLine(@"							""Allocations"": [");
            sb.AppendLine(@"								{");
            sb.AppendLine(@"									""ProfilePeriods"": [");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Oct"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2017"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 596996.5,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										},");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Apr"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2018"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 596996.5,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										}");
            sb.AppendLine(@"									],");
            sb.AppendLine(@"									""AllocationLine"": {");
            sb.AppendLine(@"										""AllocationLineCode"": ""YPD01"",");
            sb.AppendLine(@"										""AllocationLineName"": ""Academy Programme Funds""");
            sb.AppendLine(@"									},");
            sb.AppendLine(@"									""AllocationVersionNumber"": 2,");
            sb.AppendLine(@"									""AllocationStatus"": ""Approved"",");
            sb.AppendLine(@"									""AllocationAmount"": 1193993.0,");
            sb.AppendLine(@"									""AllocationLearnerCount"": null");
            sb.AppendLine(@"								}");
            sb.AppendLine(@"							]");
            sb.AppendLine(@"						},");
            sb.AppendLine(@"						{");
            sb.AppendLine(@"							""FundingPeriod"": {");
            sb.AppendLine(@"								""PeriodType"": ""FY"",");
            sb.AppendLine(@"								""PeriodId"": ""FY2017181"",");
            sb.AppendLine(@"								""StartDate"": ""2017-03-31T23:00:00+00:00"",");
            sb.AppendLine(@"								""EndDate"": ""2018-03-30T23:00:00+00:00""");
            sb.AppendLine(@"							},");
            sb.AppendLine(@"							""Allocations"": [");
            sb.AppendLine(@"								{");
            sb.AppendLine(@"									""ProfilePeriods"": [");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Oct"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2017"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 2.5,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										},");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Apr"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2018"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 2.5,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										}");
            sb.AppendLine(@"									],");
            sb.AppendLine(@"									""AllocationLine"": {");
            sb.AppendLine(@"										""AllocationLineCode"": ""YPN01"",");
            sb.AppendLine(@"										""AllocationLineName"": ""SSF - SEN Funding""");
            sb.AppendLine(@"									},");
            sb.AppendLine(@"									""AllocationVersionNumber"": 2,");
            sb.AppendLine(@"									""AllocationStatus"": ""Approved"",");
            sb.AppendLine(@"									""AllocationAmount"": 5.0,");
            sb.AppendLine(@"									""AllocationLearnerCount"": null");
            sb.AppendLine(@"								}");
            sb.AppendLine(@"							]");
            sb.AppendLine(@"						}");
            sb.AppendLine(@"					]");
            sb.AppendLine(@"				},");
            sb.AppendLine(@"				{");
            sb.AppendLine(@"					""Ukprn"": ""105024"",");
            sb.AppendLine(@"					""LAEStab"": ""3442223"",");
            sb.AppendLine(@"					""OrganisationName"": ""Pensby Junior School"",");
            sb.AppendLine(@"					""OrganisationType"": ""School"",");
            sb.AppendLine(@"					""OrganisationSubType"": ""Community"",");
            sb.AppendLine(@"					""EligiblePupils"": 0,");
            sb.AppendLine(@"					""AllocationValue"": 1194031.0,");
            sb.AppendLine(@"					""FundingPeriods"": [");
            sb.AppendLine(@"						{");
            sb.AppendLine(@"							""FundingPeriod"": {");
            sb.AppendLine(@"								""PeriodType"": ""AY"",");
            sb.AppendLine(@"								""PeriodId"": ""AY2017181"",");
            sb.AppendLine(@"								""StartDate"": ""2017-08-31T23:00:00+00:00"",");
            sb.AppendLine(@"								""EndDate"": ""2018-08-30T23:00:00+00:00""");
            sb.AppendLine(@"							},");
            sb.AppendLine(@"							""Allocations"": [");
            sb.AppendLine(@"								{");
            sb.AppendLine(@"									""ProfilePeriods"": [");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Oct"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2017"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 596996.5,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										},");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Apr"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2018"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 596996.5,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										}");
            sb.AppendLine(@"									],");
            sb.AppendLine(@"									""AllocationLine"": {");
            sb.AppendLine(@"										""AllocationLineCode"": ""YPD01"",");
            sb.AppendLine(@"										""AllocationLineName"": ""Academy Programme Funds""");
            sb.AppendLine(@"									},");
            sb.AppendLine(@"									""AllocationVersionNumber"": 2,");
            sb.AppendLine(@"									""AllocationStatus"": ""Approved"",");
            sb.AppendLine(@"									""AllocationAmount"": 1193993.0,");
            sb.AppendLine(@"									""AllocationLearnerCount"": null");
            sb.AppendLine(@"								}");
            sb.AppendLine(@"							]");
            sb.AppendLine(@"						},");
            sb.AppendLine(@"						{");
            sb.AppendLine(@"							""FundingPeriod"": {");
            sb.AppendLine(@"								""PeriodType"": ""FY"",");
            sb.AppendLine(@"								""PeriodId"": ""FY2017181"",");
            sb.AppendLine(@"								""StartDate"": ""2017-03-31T23:00:00+00:00"",");
            sb.AppendLine(@"								""EndDate"": ""2018-03-30T23:00:00+00:00""");
            sb.AppendLine(@"							},");
            sb.AppendLine(@"							""Allocations"": [");
            sb.AppendLine(@"								{");
            sb.AppendLine(@"									""ProfilePeriods"": [");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Oct"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2017"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 19.0,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										},");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Apr"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2018"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 19.0,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										}");
            sb.AppendLine(@"									],");
            sb.AppendLine(@"									""AllocationLine"": {");
            sb.AppendLine(@"										""AllocationLineCode"": ""YPN01"",");
            sb.AppendLine(@"										""AllocationLineName"": ""SSF - SEN Funding""");
            sb.AppendLine(@"									},");
            sb.AppendLine(@"									""AllocationVersionNumber"": 2,");
            sb.AppendLine(@"									""AllocationStatus"": ""Approved"",");
            sb.AppendLine(@"									""AllocationAmount"": 38.0,");
            sb.AppendLine(@"									""AllocationLearnerCount"": null");
            sb.AppendLine(@"								}");
            sb.AppendLine(@"							]");
            sb.AppendLine(@"						}");
            sb.AppendLine(@"					]");
            sb.AppendLine(@"				},");
            sb.AppendLine(@"				{");
            sb.AppendLine(@"					""Ukprn"": ""105074"",");
            sb.AppendLine(@"					""LAEStab"": ""3443335"",");
            sb.AppendLine(@"					""OrganisationName"": ""Sacred Heart Catholic Primary School"",");
            sb.AppendLine(@"					""OrganisationType"": ""School"",");
            sb.AppendLine(@"					""OrganisationSubType"": ""Voluntary"",");
            sb.AppendLine(@"					""EligiblePupils"": 0,");
            sb.AppendLine(@"					""AllocationValue"": 1194042.0,");
            sb.AppendLine(@"					""FundingPeriods"": [");
            sb.AppendLine(@"						{");
            sb.AppendLine(@"							""FundingPeriod"": {");
            sb.AppendLine(@"								""PeriodType"": ""AY"",");
            sb.AppendLine(@"								""PeriodId"": ""AY2017181"",");
            sb.AppendLine(@"								""StartDate"": ""2017-08-31T23:00:00+00:00"",");
            sb.AppendLine(@"								""EndDate"": ""2018-08-30T23:00:00+00:00""");
            sb.AppendLine(@"							},");
            sb.AppendLine(@"							""Allocations"": [");
            sb.AppendLine(@"								{");
            sb.AppendLine(@"									""ProfilePeriods"": [");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Oct"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2017"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 596996.5,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										},");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Apr"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2018"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 596996.5,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										}");
            sb.AppendLine(@"									],");
            sb.AppendLine(@"									""AllocationLine"": {");
            sb.AppendLine(@"										""AllocationLineCode"": ""YPD01"",");
            sb.AppendLine(@"										""AllocationLineName"": ""Academy Programme Funds""");
            sb.AppendLine(@"									},");
            sb.AppendLine(@"									""AllocationVersionNumber"": 2,");
            sb.AppendLine(@"									""AllocationStatus"": ""Approved"",");
            sb.AppendLine(@"									""AllocationAmount"": 1193993.0,");
            sb.AppendLine(@"									""AllocationLearnerCount"": null");
            sb.AppendLine(@"								}");
            sb.AppendLine(@"							]");
            sb.AppendLine(@"						},");
            sb.AppendLine(@"						{");
            sb.AppendLine(@"							""FundingPeriod"": {");
            sb.AppendLine(@"								""PeriodType"": ""FY"",");
            sb.AppendLine(@"								""PeriodId"": ""FY2017181"",");
            sb.AppendLine(@"								""StartDate"": ""2017-03-31T23:00:00+00:00"",");
            sb.AppendLine(@"								""EndDate"": ""2018-03-30T23:00:00+00:00""");
            sb.AppendLine(@"							},");
            sb.AppendLine(@"							""Allocations"": [");
            sb.AppendLine(@"								{");
            sb.AppendLine(@"									""ProfilePeriods"": [");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Oct"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2017"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 24.5,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										},");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Apr"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2018"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 24.5,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										}");
            sb.AppendLine(@"									],");
            sb.AppendLine(@"									""AllocationLine"": {");
            sb.AppendLine(@"										""AllocationLineCode"": ""YPN01"",");
            sb.AppendLine(@"										""AllocationLineName"": ""SSF - SEN Funding""");
            sb.AppendLine(@"									},");
            sb.AppendLine(@"									""AllocationVersionNumber"": 2,");
            sb.AppendLine(@"									""AllocationStatus"": ""Approved"",");
            sb.AppendLine(@"									""AllocationAmount"": 49.0,");
            sb.AppendLine(@"									""AllocationLearnerCount"": null");
            sb.AppendLine(@"								}");
            sb.AppendLine(@"							]");
            sb.AppendLine(@"						}");
            sb.AppendLine(@"					]");
            sb.AppendLine(@"				},");
            sb.AppendLine(@"				{");
            sb.AppendLine(@"					""Ukprn"": ""105019"",");
            sb.AppendLine(@"					""LAEStab"": ""3442216"",");
            sb.AppendLine(@"					""OrganisationName"": ""Mill Park Infant School"",");
            sb.AppendLine(@"					""OrganisationType"": ""School"",");
            sb.AppendLine(@"					""OrganisationSubType"": ""Community"",");
            sb.AppendLine(@"					""EligiblePupils"": 0,");
            sb.AppendLine(@"					""AllocationValue"": 1193998.0,");
            sb.AppendLine(@"					""FundingPeriods"": [");
            sb.AppendLine(@"						{");
            sb.AppendLine(@"							""FundingPeriod"": {");
            sb.AppendLine(@"								""PeriodType"": ""AY"",");
            sb.AppendLine(@"								""PeriodId"": ""AY2017181"",");
            sb.AppendLine(@"								""StartDate"": ""2017-08-31T23:00:00+00:00"",");
            sb.AppendLine(@"								""EndDate"": ""2018-08-30T23:00:00+00:00""");
            sb.AppendLine(@"							},");
            sb.AppendLine(@"							""Allocations"": [");
            sb.AppendLine(@"								{");
            sb.AppendLine(@"									""ProfilePeriods"": [");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Oct"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2017"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 596996.5,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										},");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Apr"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2018"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 596996.5,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										}");
            sb.AppendLine(@"									],");
            sb.AppendLine(@"									""AllocationLine"": {");
            sb.AppendLine(@"										""AllocationLineCode"": ""YPD01"",");
            sb.AppendLine(@"										""AllocationLineName"": ""Academy Programme Funds""");
            sb.AppendLine(@"									},");
            sb.AppendLine(@"									""AllocationVersionNumber"": 2,");
            sb.AppendLine(@"									""AllocationStatus"": ""Approved"",");
            sb.AppendLine(@"									""AllocationAmount"": 1193993.0,");
            sb.AppendLine(@"									""AllocationLearnerCount"": null");
            sb.AppendLine(@"								}");
            sb.AppendLine(@"							]");
            sb.AppendLine(@"						},");
            sb.AppendLine(@"						{");
            sb.AppendLine(@"							""FundingPeriod"": {");
            sb.AppendLine(@"								""PeriodType"": ""FY"",");
            sb.AppendLine(@"								""PeriodId"": ""FY2017181"",");
            sb.AppendLine(@"								""StartDate"": ""2017-03-31T23:00:00+00:00"",");
            sb.AppendLine(@"								""EndDate"": ""2018-03-30T23:00:00+00:00""");
            sb.AppendLine(@"							},");
            sb.AppendLine(@"							""Allocations"": [");
            sb.AppendLine(@"								{");
            sb.AppendLine(@"									""ProfilePeriods"": [");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Oct"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2017"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 2.5,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										},");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Apr"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2018"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 2.5,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										}");
            sb.AppendLine(@"									],");
            sb.AppendLine(@"									""AllocationLine"": {");
            sb.AppendLine(@"										""AllocationLineCode"": ""YPN01"",");
            sb.AppendLine(@"										""AllocationLineName"": ""SSF - SEN Funding""");
            sb.AppendLine(@"									},");
            sb.AppendLine(@"									""AllocationVersionNumber"": 2,");
            sb.AppendLine(@"									""AllocationStatus"": ""Approved"",");
            sb.AppendLine(@"									""AllocationAmount"": 5.0,");
            sb.AppendLine(@"									""AllocationLearnerCount"": null");
            sb.AppendLine(@"								}");
            sb.AppendLine(@"							]");
            sb.AppendLine(@"						}");
            sb.AppendLine(@"					]");
            sb.AppendLine(@"				},");
            sb.AppendLine(@"				{");
            sb.AppendLine(@"					""Ukprn"": ""105024"",");
            sb.AppendLine(@"					""LAEStab"": ""3442223"",");
            sb.AppendLine(@"					""OrganisationName"": ""Pensby Junior School"",");
            sb.AppendLine(@"					""OrganisationType"": ""School"",");
            sb.AppendLine(@"					""OrganisationSubType"": ""Community"",");
            sb.AppendLine(@"					""EligiblePupils"": 0,");
            sb.AppendLine(@"					""AllocationValue"": 1194031.0,");
            sb.AppendLine(@"					""FundingPeriods"": [");
            sb.AppendLine(@"						{");
            sb.AppendLine(@"							""FundingPeriod"": {");
            sb.AppendLine(@"								""PeriodType"": ""AY"",");
            sb.AppendLine(@"								""PeriodId"": ""AY2017181"",");
            sb.AppendLine(@"								""StartDate"": ""2017-08-31T23:00:00+00:00"",");
            sb.AppendLine(@"								""EndDate"": ""2018-08-30T23:00:00+00:00""");
            sb.AppendLine(@"							},");
            sb.AppendLine(@"							""Allocations"": [");
            sb.AppendLine(@"								{");
            sb.AppendLine(@"									""ProfilePeriods"": [");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Oct"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2017"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 596996.5,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										},");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Apr"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2018"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 596996.5,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										}");
            sb.AppendLine(@"									],");
            sb.AppendLine(@"									""AllocationLine"": {");
            sb.AppendLine(@"										""AllocationLineCode"": ""YPD01"",");
            sb.AppendLine(@"										""AllocationLineName"": ""Academy Programme Funds""");
            sb.AppendLine(@"									},");
            sb.AppendLine(@"									""AllocationVersionNumber"": 2,");
            sb.AppendLine(@"									""AllocationStatus"": ""Approved"",");
            sb.AppendLine(@"									""AllocationAmount"": 1193993.0,");
            sb.AppendLine(@"									""AllocationLearnerCount"": null");
            sb.AppendLine(@"								}");
            sb.AppendLine(@"							]");
            sb.AppendLine(@"						},");
            sb.AppendLine(@"						{");
            sb.AppendLine(@"							""FundingPeriod"": {");
            sb.AppendLine(@"								""PeriodType"": ""FY"",");
            sb.AppendLine(@"								""PeriodId"": ""FY2017181"",");
            sb.AppendLine(@"								""StartDate"": ""2017-03-31T23:00:00+00:00"",");
            sb.AppendLine(@"								""EndDate"": ""2018-03-30T23:00:00+00:00""");
            sb.AppendLine(@"							},");
            sb.AppendLine(@"							""Allocations"": [");
            sb.AppendLine(@"								{");
            sb.AppendLine(@"									""ProfilePeriods"": [");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Oct"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2017"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 19.0,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										},");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Apr"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2018"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 19.0,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										}");
            sb.AppendLine(@"									],");
            sb.AppendLine(@"									""AllocationLine"": {");
            sb.AppendLine(@"										""AllocationLineCode"": ""YPN01"",");
            sb.AppendLine(@"										""AllocationLineName"": ""SSF - SEN Funding""");
            sb.AppendLine(@"									},");
            sb.AppendLine(@"									""AllocationVersionNumber"": 2,");
            sb.AppendLine(@"									""AllocationStatus"": ""Approved"",");
            sb.AppendLine(@"									""AllocationAmount"": 38.0,");
            sb.AppendLine(@"									""AllocationLearnerCount"": null");
            sb.AppendLine(@"								}");
            sb.AppendLine(@"							]");
            sb.AppendLine(@"						}");
            sb.AppendLine(@"					]");
            sb.AppendLine(@"				},");
            sb.AppendLine(@"				{");
            sb.AppendLine(@"					""Ukprn"": ""105074"",");
            sb.AppendLine(@"					""LAEStab"": ""3443335"",");
            sb.AppendLine(@"					""OrganisationName"": ""Sacred Heart Catholic Primary School"",");
            sb.AppendLine(@"					""OrganisationType"": ""School"",");
            sb.AppendLine(@"					""OrganisationSubType"": ""Voluntary"",");
            sb.AppendLine(@"					""EligiblePupils"": 0,");
            sb.AppendLine(@"					""AllocationValue"": 1194042.0,");
            sb.AppendLine(@"					""FundingPeriods"": [");
            sb.AppendLine(@"						{");
            sb.AppendLine(@"							""FundingPeriod"": {");
            sb.AppendLine(@"								""PeriodType"": ""AY"",");
            sb.AppendLine(@"								""PeriodId"": ""AY2017181"",");
            sb.AppendLine(@"								""StartDate"": ""2017-08-31T23:00:00+00:00"",");
            sb.AppendLine(@"								""EndDate"": ""2018-08-30T23:00:00+00:00""");
            sb.AppendLine(@"							},");
            sb.AppendLine(@"							""Allocations"": [");
            sb.AppendLine(@"								{");
            sb.AppendLine(@"									""ProfilePeriods"": [");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Oct"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2017"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 596996.5,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										},");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Apr"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2018"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 596996.5,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										}");
            sb.AppendLine(@"									],");
            sb.AppendLine(@"									""AllocationLine"": {");
            sb.AppendLine(@"										""AllocationLineCode"": ""YPD01"",");
            sb.AppendLine(@"										""AllocationLineName"": ""Academy Programme Funds""");
            sb.AppendLine(@"									},");
            sb.AppendLine(@"									""AllocationVersionNumber"": 2,");
            sb.AppendLine(@"									""AllocationStatus"": ""Approved"",");
            sb.AppendLine(@"									""AllocationAmount"": 1193993.0,");
            sb.AppendLine(@"									""AllocationLearnerCount"": null");
            sb.AppendLine(@"								}");
            sb.AppendLine(@"							]");
            sb.AppendLine(@"						},");
            sb.AppendLine(@"						{");
            sb.AppendLine(@"							""FundingPeriod"": {");
            sb.AppendLine(@"								""PeriodType"": ""FY"",");
            sb.AppendLine(@"								""PeriodId"": ""FY2017181"",");
            sb.AppendLine(@"								""StartDate"": ""2017-03-31T23:00:00+00:00"",");
            sb.AppendLine(@"								""EndDate"": ""2018-03-30T23:00:00+00:00""");
            sb.AppendLine(@"							},");
            sb.AppendLine(@"							""Allocations"": [");
            sb.AppendLine(@"								{");
            sb.AppendLine(@"									""ProfilePeriods"": [");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Oct"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2017"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 24.5,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										},");
            sb.AppendLine(@"										{");
            sb.AppendLine(@"											""Period"": ""Apr"",");
            sb.AppendLine(@"											""Occurrence"": 1,");
            sb.AppendLine(@"											""PeriodYear"": ""2018"",");
            sb.AppendLine(@"											""PeriodType"": ""CalendarMonth"",");
            sb.AppendLine(@"											""ProfileValue"": 24.5,");
            sb.AppendLine(@"											""DistributionPeriod"": ""2017-2018""");
            sb.AppendLine(@"										}");
            sb.AppendLine(@"									],");
            sb.AppendLine(@"									""AllocationLine"": {");
            sb.AppendLine(@"										""AllocationLineCode"": ""YPN01"",");
            sb.AppendLine(@"										""AllocationLineName"": ""SSF - SEN Funding""");
            sb.AppendLine(@"									},");
            sb.AppendLine(@"									""AllocationVersionNumber"": 2,");
            sb.AppendLine(@"									""AllocationStatus"": ""Approved"",");
            sb.AppendLine(@"									""AllocationAmount"": 49.0,");
            sb.AppendLine(@"									""AllocationLearnerCount"": null");
            sb.AppendLine(@"								}");
            sb.AppendLine(@"							]");
            sb.AppendLine(@"						}");
            sb.AppendLine(@"					]");
            sb.AppendLine(@"				}");
            sb.AppendLine(@"			],");
            sb.AppendLine(@"			""TotalAllocation"": 7164142.0");
            sb.AppendLine(@"		}");
            sb.AppendLine(@"	],");
            sb.AppendLine(@"	""TotalAllocation"": 7164142.0");
            sb.AppendLine(@"}");

            return sb.ToString();
        }
    }

  
}